Controllers/PfeController.cs
using ASP.NETCoreIdentityCustom.Areas.Identity.Data;
using ASP.NETCoreIdentityCustom.Core;
using ASP.NETCoreIdentityCustom.Core.ViewModels;
using ASP.NETCoreIdentityCustom.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using static ASP.NETCoreIdentityCustom.Core.Constants;



namespace ASP.NETCoreIdentityCustom.Controllers
{
    public class PfeController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<HomeController> _logger;
        private readonly UserManager<ApplicationUser> _userManager;



        public PfeController(ApplicationDbContext context, ILogger<HomeController> logger, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _logger = logger;
            _userManager = userManager;
        }
        [Authorize(Roles = $"{Constants.Roles.Teacher},{Constants.Roles.Student}")]
        public async Task<IActionResult> IndexAsync()
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier);

            var user = await _userManager.FindByIdAsync(userId.Value);
            var userRole = await _userManager.GetRolesAsync(user);
            if (userRole[0] == "Student")
                {
                    return RedirectToAction("Student");
                }
                else
                {
                    return RedirectToAction(nameof(Teacher));
                }
            return RedirectToAction("Index","Home");
        }

        [Authorize(Policy = Constants.Policies.RequireStudent)]
        public async Task<IActionResult> StudentAsync()
        {
            var user = await _userManager.GetUserAsync(User);
            var project = await _context.Project.Where(p => p.ApplicationUserId == user.Id).FirstOrDefaultAsync();

            if(project == null)
            {
                ViewBag.ProjectDescription = "No project";
                ViewBag.ProjectDomaine = "No project";
                ViewBag.Supervisor = "No Supervisor";
            }
            else
            {
                var projectDomaine = _context.Domaine.Where(d => d.Id == project.DomaineId).First();
                ViewBag.ProjectDescription = project.DescriptionProjet;
                ViewBag.ProjectDomaine = projectDomaine.Name;
                var supervisorId = project.TeacherId;
                if (supervisorId == null)
                {
                    ViewBag.Supervisor = "No Supervisor";
                }
                else
                {
                    var supervisor = await _context.ApplicationUser.FindAsync(supervisorId);
                    ViewBag.Supervisor = supervisor.FirstName + " " +supervisor.LastName;
                }
            }
           
            ViewBag.FirstName = user.FirstName;
            ViewBag.LastName = user.LastName;
            ViewBag.Description = user.Description;
            ViewBag.Email = user.Email;

            return View();

        }

        [Authorize(Policy = Constants.Policies.RequireStudent)]
        public async Task<IActionResult> MyProjectAsync()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);//current user id
            var project = await _context.Project
                .Include(p => p.ApplicationUser)
                .FirstOrDefaultAsync(m => m.ApplicationUserId == userId);

            var selectListItems = _context.Domaine.Select(r => new SelectListItem
            {
                Value = r.Id.ToString(),
                Text = r.Name
            });
            ViewData["DomaineId"] = new SelectList(selectListItems, "Value", "Text");
            ViewBag.UserID = userId;
            return View(project);
        }

        [Authorize(Policy = Constants.Policies.RequireStudent)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditProject([Bind("ProjectId,DescriptionProjet,DomaineId,Title")] Project project)
        {

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);//current user id
            var StudentProject = await _context.Project
                .Include(p => p.ApplicationUser)
                .FirstOrDefaultAsync(m => m.ApplicationUserId == userId);
            if (StudentProject == null)
            {
                project.ApplicationUserId = userId;
                _context.Add(project);
                await _context.SaveChangesAsync();
                return RedirectToAction("Student");
            }
            else
            {
                var projectId = StudentProject.ProjectId;
                _context.ChangeTracker.Clear();
                project.ApplicationUserId = userId;

                _context.Update(project);
                await _context.SaveChangesAsync();
                return RedirectToAction("Student");
            }
        }

        [Authorize(Policy = "RequireTeacher")]
        public IActionResult Teacher()
        {
            var user = _userManager.GetUserAsync(User);
            ViewBag.FullName = user.Result.FirstName + user.Result.LastName;
            ViewBag.Email = user.Result.Email;
            return View();
        }
       

        [Authorize(Policy = "RequireTeacher")]
        public IActionResult ProjectsList()
        {
            var user = _userManager.GetUserAsync(User);
            var teacherProjects = (from a in _context.ApplicationUser
                                       where a.Id == user.Result.Id
                                       join td in _context.TeacherDomaines
                                       on a.Id equals td.ApplicationUserId
                                       join d in _context.Domaine
                                       on td.DomaineId equals d.Id
                                       join p in _context.Project
                                       on d.Id equals p.DomaineId
                                       where p.TeacherId == null
                                       join s in _context.ApplicationUser
                                       on p.ApplicationUserId equals s.Id
                                       select new {
                                       s.FirstName,
                                       s.LastName,
                                       p.ProjectId,
                                       a.Id,
                                       p.DescriptionProjet,
                                       p.Title,
                                       d.Name
                                       } ).ToList();
            
            ViewBag.TeacherProjects = teacherProjects;

            return View();
        }
        [Authorize(Policy = Constants.Policies.RequireTeacher)]
        [HttpPost]
        public async Task<IActionResult> AcceptProject(int ProjectId,string TeacherId)
        {
            var numberOfAcceptedProjects = _context.Project.Where(p => p.TeacherId == TeacherId).Count();
            if(numberOfAcceptedProjects == 5) 
                {
                    TempData ["Message"] = "You have already chose 5 projects";
                    return RedirectToAction("ProjectsList");
                }
            var project = await _context.Project.FindAsync(ProjectId);
            project.TeacherId = TeacherId;
            _context.Update(project);
            await _context.SaveChangesAsync();
            return RedirectToAction("ProjectsList");
        }

        [Authorize(Policy = "RequireTeacher")]
        public async Task<IActionResult> DomainesAsync()
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var user = await _userManager.FindByIdAsync(userId);

            var teacherdomaines = (from a in _context.ApplicationUser
                                   where a.Id == userId
                                    join td in _context.TeacherDomaines
                                    on a.Id equals td.ApplicationUserId
                                    join d in _context.Domaine
                                    on td.DomaineId equals d.Id
                                    select d.Name).ToList();

            var domaines = _context.Domaine.ToList();

            var domaineItems = domaines.Select(domaine =>
                new SelectListItem(
                    domaine.Name,
                    domaine.Id.ToString(),
                    teacherdomaines.Any(td => td.Contains(domaine.Name)))).ToList();

            TeacherDomaineViewModel TdModel = new TeacherDomaineViewModel
            {
                ApplicationUser = user,
                Domaines = domaineItems,
            };

            return View(TdModel);
        }



        [Authorize(Policy = Constants.Policies.RequireTeacher)]
        public async Task<IActionResult> AcceptedProjects()
        {
            var user = await _userManager.GetUserAsync(User);

            //var acceptedProjects = (from a in _context.ApplicationUser)

            var acceptedProjects = (from a in _context.ApplicationUser
                                   where a.Id == user.Id
                                   join td in _context.TeacherDomaines
                                   on a.Id equals td.ApplicationUserId
                                   join d in _context.Domaine
                                   on td.DomaineId equals d.Id
                                   join p in _context.Project
                                   on d.Id equals p.DomaineId
                                   where p.TeacherId == user.Id
                                   join s in _context.ApplicationUser
                                   on p.ApplicationUserId equals s.Id
                                   select new
                                   {

Controllers/UserController.cs
using ASP.NETCoreIdentityCustom.Areas.Identity.Data;
using ASP.NETCoreIdentityCustom.Core;
using ASP.NETCoreIdentityCustom.Core.Repositories;
using ASP.NETCoreIdentityCustom.Core.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ASP.NETCoreIdentityCustom.Controllers
{
    [Authorize(Policy = Constants.Policies.RequireAdmin)]
    public class UserController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly SignInManager<ApplicationUser> _signInManager;

        public UserController(IUnitOfWork unitOfWork, SignInManager<ApplicationUser> signInManager)
        {
            _unitOfWork = unitOfWork;
            _signInManager = signInManager;
        }

        public IActionResult Index()
        {
            var users = _unitOfWork.User.GetUsers();
            return View(users);
        }

        public async Task<IActionResult> Edit(string id)
        {
            var user = _unitOfWork.User.GetUser(id);
            var roles = _unitOfWork.Role.GetRoles();

            var userRoles = await _signInManager.UserManager.GetRolesAsync(user);

            var roleItems = roles.Select(role =>
                new SelectListItem(
                    role.Name,
                    role.Id,
                    userRoles.Any(ur => ur.Contains(role.Name)))).ToList();

            var vm = new EditUserViewModel
            {
                User = user,
                Roles = roleItems
            };

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> OnPostAsync(EditUserViewModel data)
        {
            var user = _unitOfWork.User.GetUser(data.User.Id);
            if (user == null)
            {
                return NotFound();
            }

            var userRolesInDb = await _signInManager.UserManager.GetRolesAsync(user);

            //Loop through the roles in ViewModel
            //Check if the Role is Assigned In DB
            //If Assigned -> Do Nothing
            //If Not Assigned -> Add Role

            var rolesToAdd = new List<string>();
            var rolesToDelete = new List<string>();

            foreach (var role in data.Roles)
            {
                var assignedInDb = userRolesInDb.FirstOrDefault(ur => ur == role.Text);
                if (role.Selected)
                {
                    if (assignedInDb == null)
                    {
                        rolesToAdd.Add(role.Text);
                    }
                }
                else
                {
                    if (assignedInDb != null)
                    {
                        rolesToDelete.Add(role.Text);
                    }
                }
            }

            if (rolesToAdd.Any())
            {
                await _signInManager.UserManager.AddToRolesAsync(user, rolesToAdd);
            }

            if (rolesToDelete.Any())
            {
                await _signInManager.UserManager.RemoveFromRolesAsync(user, rolesToDelete);
            }

            user.FirstName = data.User.FirstName;
            user.LastName = data.User.LastName;
            user.Email = data.User.Email;

            _unitOfWork.User.UpdateUser(user);

            return RedirectToAction("Edit", new { id = user.Id });
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using ASP.NETCoreIdentityCustom.Areas.Identity.Data

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ENIS - ECOLE NATIONALE D'INGENIEURS DE SFAX</title>
    <link rel = "icon" href = "https://upload.wikimedia.org/wikipedia/fr/d/d9/Logo_ENIS_Sfax.png" type = "image/x-icon">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASP.NETCoreIdentityCustom.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/image/logo_enis_sfax.png" width="30" /></a>
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Manage Users</a>
                            </li> 
                        }
                        @if (User.IsInRole("Student") || User.IsInRole("Teacher"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Pfe" asp-action="Index">Pfe</a>
                            </li>
                        }

                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">About Us</a>
                        </li>
                    </ul>
                </div>
                <partial name="_LoginPartial"/>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Ecole National d'ingénieurs de Sfax - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>